name: Enforce Branch Naming Convention

on:
  push:
    branches: [ '**' ]

jobs:
  enforce-naming:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate Branch Name
        run: |
          branch_name=$(git rev-parse --abbrev-ref HEAD)
          if ! [[ $branch_name =~ ^feature/|^bugfix/|^hotfix/ ]]; then
            echo "Branch name does not conform to the naming convention. Please use feature/, bugfix/, or hotfix/ prefix."
            exit 1
          fi
