name: Enforce Branch Naming Convention

on:
  create:
    branches: [main]

jobs:
  check_branch_name:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |
          branch_name=$(echo "${{ github.head_ref }}" | sed 's/refs\/heads\///')
          echo "Branch name: $branch_name"
          if [[ ! "$branch_name" =~ ^(feature|bugfix|hotfix|release|chore)\/[a-z0-9-]+$ ]]; then
            echo "Error: Branch name '$branch_name' does not match the naming convention."
            exit 1
          fi
