---
name: Enforce Branch Naming Convention
on:
  create:
    branches: ['*']
jobs:
  check_branch_name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures full history        
          
      - name: Check branch name & Delete if not in Standard
        run: >
          branch_name=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')
          
          echo "❌ Deleting invalid branch: $branch_name"
          
          if [[ ! "$branch_name" =~ ^(feature|bugfix|hotfix|release|chore)\/[a-z0-9-]+$ ]]; then
            
            echo "Error: Branch name '$branch_name' does not match the naming convention. So its deleted automatically"
            
            git branch -D "$branch_name" || echo "⚠️ Failed to delete $branch_name"
            
            git push origin --delete $branch_name
            
            env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
            exit 1
          fi
