---
name: Release Management Process Checks
on:
  create:
    branches:
      - "*"
    pull_request:
      - - opened
        - synchronize
        - reopened
        - labeled
        - unlabeled
jobs:
  workflow-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Workflow Triggered
        run: echo workflow triggered
  branch-naming-policy:
    needs:
      - workflow-trigger
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check branch name & Delete if not in Standard
        run: >
          branch_name=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///') 
          echo "Branch Name: $branch_name" 
          if [[ ! "$branch_name" =~ ^(r|fb|hb|us)[0-9]+[-a-z]+$ ]]; then  
            echo "❌ Error: Branch name '$branch_name' does not match the naming convention."
              git push origin --delete $branch_name
              exit 1
            else
              echo "✅ Branch name '$branch_name' created & its match the naming convention, Proceed. "
          fi
  check-label:
    needs:
      - workflow-trigger
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get PR number
        id: pr_number
        run: echo "::set-output name=number::$(echo "$GITHUB_REF" | cut -d '/' -f 3)"

      - name: Get PR labels
        id: get_pr_labels
        run: |
          labels=$(gh api --jq '.labels.[].name' /repos/${{ github.repository }}/pulls/${{ steps.pr_number.outputs.number }})
          echo "::set-output name=labels::$labels"

      - name: Use the labels
        run: |
          echo "Labels: ${{ steps.get_pr_labels.outputs.labels }}"
          # You can now use the labels in your workflow
          # For example, you can check if a specific label exists:
          if [[ "${{ steps.get_pr_labels.outputs.labels }}" == "" ]]; then
              echo "❌ Error: PR Label is missing. Please add a label to the PR."
              exit 1
          fi
